In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('Data.csv')

In [8]:
df.head()

,SYMBOL \n,OPEN \n,HIGH \n,LOW \n,PREV. CLOSE \n,LTP \n,INDICATIVE CLOSE \n,CHNG \n,%CHNG \n,VOLUME \n(shares),VALUE \n (₹ Crores),52W H \n,52W L \n,30 D %CHNG \n,365 D % CHNG \n
0,NIFTY 50,"25,546.85","25,781.50","25,508.60","25,585.30","25,709.85",-,124.55,0.49,"42,20,55,809","35,106.78","25,781.50","21,743.65",1.87,2.96
1,ASIANPAINT,"2,421.00","2,544.00","2,421.00","2,409.70","2,507.80",-,98.10,4.07,"37,19,960",933.45,"3,103.55","2,124.75",1.08,-18.63
2,M&M,"3,561.00","3,656.00","3,560.10","3,560.80","3,656.00",-,95.20,2.67,"33,39,579","1,212.21","3,723.80","2,425.00",1.09,18.88
3,BHARTIARTL,"1,973.60","2,034.30","1,970.30","1,967.40","2,012.90",-,45.50,2.31,"67,43,801","1,358.03","2,045.80","1,511.00",3.74,16.04
4,MAXHEALTH,"1,188.00","1,212.80","1,178.70","1,175.30","1,201.00",-,25.70,2.19,"52,39,734",626.16,"1,314.30",888.90,3.80,24.74

In [9]:
df.head(4).tail(1)

,SYMBOL \n,OPEN \n,HIGH \n,LOW \n,PREV. CLOSE \n,LTP \n,INDICATIVE CLOSE \n,CHNG \n,%CHNG \n,VOLUME \n(shares),VALUE \n (₹ Crores),52W H \n,52W L \n,30 D %CHNG \n,365 D % CHNG \n
3,BHARTIARTL,"1,973.60","2,034.30","1,970.30","1,967.40","2,012.90",-,45.5,2.31,"67,43,801","1,358.03","2,045.80","1,511.00",3.74,16.04

In [10]:
df.head(2)

,SYMBOL \n,OPEN \n,HIGH \n,LOW \n,PREV. CLOSE \n,LTP \n,INDICATIVE CLOSE \n,CHNG \n,%CHNG \n,VOLUME \n(shares),VALUE \n (₹ Crores),52W H \n,52W L \n,30 D %CHNG \n,365 D % CHNG \n
0,NIFTY 50,"25,546.85","25,781.50","25,508.60","25,585.30","25,709.85",-,124.55,0.49,"42,20,55,809","35,106.78","25,781.50","21,743.65",1.87,2.96
1,ASIANPAINT,"2,421.00","2,544.00","2,421.00","2,409.70","2,507.80",-,98.10,4.07,"37,19,960",933.45,"3,103.55","2,124.75",1.08,-18.63