In [1]:
import pandas as pd

In [123]:
dff = pd.read_csv('Data_emp.csv')

In [124]:
dff

   emp_id name  salary dept_name country
0       1    A   200.0        IT     USA
1       2    B   100.0        HR   India
2       3    C   400.0        IT   India
3       4    D   500.0        IT   India
4       5    E   400.0        HR   India
5       6    F   600.0     Admin     USA
6       7    G   700.0        IT     USA
7       8  NaN   100.0       NaN     NaN
8       9    J   500.0       NaN     USA

In [125]:
g=dff.groupby('dept_name')

In [129]:
g['dept_name'].count()

dept_name
Admin    1
HR       2
IT       4
Name: dept_name, dtype: int64

In [134]:
#def NullValueCheck():
 # assert  dff['name'].isnull.all(), "Found Null Value"

In [148]:
dff['name'].notnull()

0     True
1     True
2     True
3     True
4     True
5     True
6     True
7    False
8     True
Name: name, dtype: bool

In [149]:
dff[dff['name'].notnull()]

   emp_id name  salary dept_name country
0       1    A   200.0        IT     USA
1       2    B   100.0        HR   India
2       3    C   400.0        IT   India
3       4    D   500.0        IT   India
4       5    E   400.0        HR   India
5       6    F   600.0     Admin     USA
6       7    G   700.0        IT     USA
8       9    J   500.0       NaN     USA

In [150]:
dff['salary'].duplicated()

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7     True
8     True
Name: salary, dtype: bool

In [151]:
dup = dff[dff['salary'].duplicated()]

In [152]:
dup

   emp_id name  salary dept_name country
4       5    E   400.0        HR   India
7       8  NaN   100.0       NaN     NaN
8       9    J   500.0       NaN     USA