In [1]:
import pandas as pd

In [41]:
df =pd.read_csv('Data_emp.csv')

In [42]:
df

   emp_id name  salary dept_name country
0     1.0    A     200        IT     USA
1     2.0    B     100        HR   India
2     3.0    C     400        IT   India
3     4.0    D     500        IT   India
4     5.0    E     400        HR   India
5     6.0    F     600     Admin     USA
6     7.0    G     700        IT     USA
7     NaN  NaN     100       NaN     NaN
8     9.0    J     500       NaN     USA
9     1.0    A     200        IT     USA

In [43]:
g=df.groupby('dept_name')

In [44]:
g['dept_name'].count()

dept_name
Admin    1
HR       2
IT       5
Name: dept_name, dtype: int64

In [45]:
len(df)

10

In [46]:
df.columns

Index(['emp_id', 'name', 'salary', 'dept_name', 'country'], dtype='object')

In [47]:
g=df.groupby('dept_name')

In [48]:
g['dept_name'].sum()

dept_name
Admin         Admin
HR             HRHR
IT       ITITITITIT
Name: dept_name, dtype: object

In [49]:
g['emp_id'].count()

dept_name
Admin    1
HR       2
IT       5
Name: emp_id, dtype: int64

In [50]:
g['name'].count()

dept_name
Admin    1
HR       2
IT       5
Name: name, dtype: int64

In [55]:
df['emp_id'].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan,  9.])

In [56]:
len(df['emp_id'].unique())

9

In [57]:
df['emp_id']

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    NaN
8    9.0
9    1.0
Name: emp_id, dtype: float64

In [58]:
df['emp_id']

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    7.0
7    NaN
8    9.0
9    1.0
Name: emp_id, dtype: float64

In [60]:
len(df['emp_id'])

10

In [61]:
df['emp_id'].unique()

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7., nan,  9.])

In [62]:
len(df['emp_id'].unique())

9

In [64]:
df.shape

(10, 5)

In [65]:
df.iloc[[2,4],[1]]

  name
2    C
4    E

In [69]:
df['salary'].nlargest(2)

6    700
5    600
Name: salary, dtype: int64

In [70]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
dtype: bool

In [74]:
dup=df[df.duplicated()]

In [76]:
dup

   emp_id name  salary dept_name country
9     1.0    A     200        IT     USA

In [81]:
dup2=df[df['emp_id'].duplicated()]

In [83]:
dup2

   emp_id name  salary dept_name country
9     1.0    A     200        IT     USA